### ISSUE TITLE
Update website to point to correct release

### ISSUE THREAD

**Issue by stdedos** [Code52/carnac#111]
Using Carnac.application (sandbox-installed it and grabbed the executables out) works perfectly, instead of github-portable zip. They don't even have the same size.

Windows 8.1 Update 1, Fully updated

A (cluttered, unfortunatelly) screenshot tells all the differences:
![image](https://cloud.githubusercontent.com/assets/133706/15094036/39576076-14a1-11e6-8765-17a8aedcbab9.png)

**Comment by shiftkey** [comment]
@stdedos it's not clear to me where you found the problem version. Could you share where you found it, and what the version the `.exe` is?

**Comment by stdedos** [comment]
![image](https://cloud.githubusercontent.com/assets/133706/15177186/889d7958-1777-11e6-9f96-eb20efe68558.png) http://code52.org/carnac/ is the link

Version numbers are both the same (1.0.0.0) but file size of this file is 2.29 MB (instead of 3.20 MB of the working version)

**Comment by shiftkey** [comment]
@stdedos ok, thanks for the information. It looks like we're still using the Downloads API (long obsoleted by GitHub) and it should be migrated to downloading the latest release. I've updated the title to make this a bit clearer.

**Comment by stdedos** [comment]
Cool! Whatever helps you remember/clarify (I usually use stupid/funny names to whom it may make laugh XD)

**Comment by shiftkey** [comment]
Closing this now that we have a proper website and opened https://github.com/Code52/carnackeys.github.io/issues/14 to track updating the installer details.
