### ISSUE TITLE
Don't display key presses on password inputs

### ISSUE THREAD

**Issue by sergeyzwezdin** [Code52/carnac#113]
This tool is quite useful for presentation, but I don't like it displays my password when I type it :-)

Could you consider ability to avoid displaying if I'm typing in password input (both for win-app and in-browser app)?

**Comment by shiftkey** [comment]
Interesting idea, but I'm not sure we can detect the type of input you're interacting with.

I'm open to alternative UI/UX ideas around this - maybe making it easier to mute the keyboard events would be a helpful solutions here?

**Comment by alfhenrik** [comment]
Looks like there is a keyboard combination to enter "password" mode `Ctrl+Alt+P` https://github.com/Code52/carnac/blob/master/src/Carnac.Logic/PasswordModeService.cs#L21

**Comment by shiftkey** [comment]
@alfhenrik cool, looks like we just need some docs to identify these sorts of features :metal:

Closing this out unless others have suggestions.
