### ISSUE TITLE
Displays phantom monitors in preferences window

### ISSUE THREAD

**Issue by JasonKleban** [Code52/carnac#119]
![image](https://cloud.githubusercontent.com/assets/17498172/20848544/8baf04d4-b8a0-11e6-9727-00355b52b063.png)

**Comment by celeron533** [comment]
I believe it is a Windows level thing, such as the driver's issue or you have plugged an adapter?

**Comment by shiftkey** [comment]
Without more information about reproducing this I'm not sure where to start.

@JasonKleban if you can share some more information about your setup I'll reopen this and try and get to the bottom of what's happening here.

**Comment by JasonKleban** [comment]
I just have two monitors, one big LG ultra wide screen and a standard looking dell.  I just think there ought to be a sanity check that monitors of a very small size, such as 0 x 0, should be ignored?  It's not a big deal.
