### ISSUE TITLE
log to file

### ISSUE THREAD

**Issue by gMan1990** [Code52/carnac#120]

**Comment by celeron533** [comment]
Key logging is not a good idea.

**Comment by shiftkey** [comment]
> Key logging is not a good idea.

Agreed

**Comment by snowman** [comment]
don't agree

**Comment by snowman** [comment]
With logging, you can analyze the data when using *carnac* on the long trip, for example:

1. Which app do you spend most of the time a day/week/month
2. What's your most productive time range using visual graph
3. Forgotten password
4. When did I search for something on Chrome
5. etc

I also use [FastCapture Recorder](https://www.faststone.org/FSCaptureDetail.htm) to record what I doing in a day, sometimes I make a mistake, I can check the recording back like wrong git operation
