### ISSUE TITLE
move installer over to GitHub releases

### ISSUE THREAD

**Issue by shiftkey** [Code52/carnac#125]
We don't actually need any external infrastructure for the installer. Mostly because I'm not sure when the last time was that we published there, and if the original link even works.

Here's my current thinking - use `Squirrel.Windows` and GitHub releases.

This [guide](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/github.md) is what I'd start working from, but the other tasks include:

 - update the website to refer to `https://github.com/Code52/carnac/releases/latest`
 - ???

**Comment by alfhenrik** [comment]
I'll take this one
