### ISSUE TITLE
checksum the file and add it to the chocolatey installer

### ISSUE THREAD

**Issue by shiftkey** [Code52/carnac#135]
For an example of this: https://github.com/shiftkey/chocolatey-beyondcompare/blob/76ad6c026584b88e852cec030119bfb3b89da1e6/src/tools/chocolateyInstall.ps1

**Comment by shiftkey** [comment]
Actually this will be so much easier to do once we move over to CAKE using [`FileHash`](http://develop.cakebuild.net/api/Cake.Common.Security/FileHash/)...

**Comment by GlassGruber** [comment]
Sorry for bumping this, can you publish the checksum signature for the compiled Setup.exe file also in the README or somewhere?

Thank you!

**Comment by hnrkndrssn** [comment]
Hi @GlassGruber,

I've raised https://github.com/Code52/carnac/issues/203 to add the checksum _somewhere_ more accessible as well.

Cheers,
Henrik

**Comment by GlassGruber** [comment]
Nice! I didn't open a new issue because I thought that maybe was already implemented somewhere (and tbh I found a virustotal link with signature on chocolatey page so I used that).
Thank you for your time!
