### ISSUE TITLE
Not working with Visual Studio Professional 2017

### ISSUE THREAD

**Issue by erkantaylan** [Code52/carnac#153]
carnac works at everywhere but vs2017 pro
I have VS Pro 2017 Version 15.2 (26430.6) 

They did something, a few months ago after I update vs [`autohortkey`](https://github.com/AutoHotkey/AutoHotkey) stopped working too.

**Comment by shiftkey** [comment]
> carnac works at everywhere but vs2017 pro

Not sure what you mean by "works" here. Does the solution not open? Or does carnac not work at runtime? Any errors you see would also be helpful to isolate the issue (Event Viewer might have some information too).

**Comment by erkantaylan** [comment]
I mean program runs but does not get any key record. `Keys` tab shows nothing while I'm using VS2017.
But in all other programs works great.

**Comment by erkantaylan** [comment]
I was running VS as admin because my program needs admin rights. tried to run carnac as admin but you have already an issue for that #115.

Btw can you give some keywords to how did you do this -> I cannot click pressed key list window, when I click it goes below.

**Comment by celeron533** [comment]
I remember Carnac is not able to get the key if the target program is running under Admin privilege.

**Comment by bfritscher** [comment]
I think it is working but the settings are bugged see https://github.com/Code52/carnac/pull/151
remove the visual-studio.yml from the keymaps folder or try my version from the fork.

**Comment by erkantaylan** [comment]
@bfritscher your fork is not working too, it is about `running as admin` it I don't run VS as admin, carnac works.

**Comment by bfritscher** [comment]
Ok so what is the problem with running carmac run as admin? I tested it with carmac as admin and notepad as admin and it got the keys. Is there something different with visual studio?

**Comment by erkantaylan** [comment]
I'm sure carnac was not starting when I run it as admin but it works now. You can close the issue. I am able to run carnac as admin and it works with vs2017 and with other apps too.

**Comment by alfhenrik** [comment]
Closing this issue as solution is not crashing anymore when run as admin
