### ISSUE TITLE
Feature Request: Show and persist meta keys (Sticky Keys) like on Mac

### ISSUE THREAD

**Issue by odjhey** [Code52/carnac#154]
I use sticky keys.
Feature request for the following scenarios.
When using shift/ctrl/alt/windows (show on screen until followed by a character)
When double tap shift (lock shift in sticky keys) (keep shift icon on screen)

**Comment by bfritscher** [comment]
Hi @odjhey can you try out my test version and give feedback? https://github.com/bfritscher/carnac/releases/tag/v3-beta
