### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by hnrkndrssn** [Code52/carnac#166]
Currently every commit to `master` creates a new release, we should probably change this so we can bundle changes into a larger release instead.

A couple of options:
- Merge changes to a `release` branch and once tested merge that branch to `master`
- Merge changes to `master` and use tags to trigger release creation
- ???

Also, would be nice to start including release notes for the releases 😃 

cc @shiftkey

**Comment by shiftkey** [comment]
I'm not hugely fussed with the current process, but I wouldn't recommend adding making the workflow more complicated. :thumbsup: to [publishing tagged releases](https://www.appveyor.com/docs/deployment/github/#release-every-tag-build) if you want better control over that.

**Comment by celeron533** [comment]
I prefer the TAG option :)

**Comment by q2apro** [comment]
Maybe it is also possible to have a `dist` folder that holds the exe file, ready for all standard users.

**Comment by hnrkndrssn** [comment]
Releases will now only be created when a tag is built in AppVeyor
