### ISSUE TITLE
pop fade delay does not work,how to Solve it?

### ISSUE THREAD

**Issue by kakaluote444** [Code52/carnac#176]
**I have set pop fade delay setting item,but it seems doesn't  work.How to config my setting item?**

**Comment by kakaluote444** [comment]
sorry for my poor english.

**Comment by celeron533** [comment]
一般建议在提问题的时候把问题的核心下载标题里，比如“pop fade delay does not work”
It is recommend to summarize your question in the title, such as "pop fade delay does not work"

Tested on my machine.
You need to restart the program to activate new settings.

**Comment by kakaluote444** [comment]
@celeron533 thanks very much,it really work after restart.e....,i have another question that can it support single line show shortcut key?beacause i want it show in single line that means the latest shortcut key will override the old shortcut key,not show in a multiple line way.

**Comment by celeron533** [comment]
nope. Unless you modify the source code.

**Comment by kakaluote444** [comment]
@celeron533 haha, it's still good enough.

**Comment by kakaluote444** [comment]
@celeron533 哈哈，原来你是上海人。。。。。

**Comment by zackhall** [comment]
This was super helpful actually to see this issue ticket. Didn't realize it would need to be restarted as all the other options took effect right away. Might be worth adding a comment or note in the settings panel itself to make people using the program aware of this.
