### ISSUE TITLE
GitHub auth token needs to be created and encrypted by the right account

### ISSUE THREAD

**Issue by hnrkndrssn** [Code52/carnac#209]
Turns out that the owner of the build needs to create the encrypted secrets stored in `appveyor.yml` and as I updated them with encrypted secrets from my account it caused the build to fail...😭 https://ci.appveyor.com/project/shiftkey/carnac/builds/23918521

@shiftkey sorry, but it seems I need you to re-create a GitHub auth token and encrypt it in appveyor and update the values in `appveyor.yml`... 😳 (I had to update the auth token as it was complaining about it no longer being valid)

**Comment by shiftkey** [comment]
@hnrkndrssn oops, hopefully #210 should fix this - otherwise feel free to migrate to your own Appveyor account if you'd prefer to manage it yourself.

**Comment by hnrkndrssn** [comment]
Thanks @shiftkey, I might do that once things around here have calmed down a bit. Will let you know.
