### ISSUE TITLE
Windows key break layout

### ISSUE THREAD

**Issue by jueti** [Code52/carnac#217]
**Describe**
Button "Win" has a unusual size.
![image](https://user-images.githubusercontent.com/24526369/59333254-8c177080-8d2a-11e9-98ab-38f81ede2ec8.png)

**Environment**
Win 10 Pro Workstation 1809 (June Update)
Carnaac 2.3.3.0

**Configuration**
![image](https://user-images.githubusercontent.com/24526369/59333208-6db17500-8d2a-11e9-9e55-3edb566c71d0.png)

**Comment by Thunder242** [comment]
#114 #215 #114

**Comment by bfritscher** [comment]
Hi you can try my fork I fixed it for my mouse key display, but the side effect is that it also applies to the windows logo
https://github.com/bfritscher/carnac/releases

**Comment by jueti** [comment]
> Hi you can try my fork I fixed it for my mouse key display, but the side effect is that it also applies to the windows logo
> https://github.com/bfritscher/carnac/releases

👍 Pretty work!

Thank you!
