### ISSUE TITLE
Carnac.exe - Assert Failure (downloaded from homepage)

### ISSUE THREAD

**Issue by stephen147** [Code52/carnac#219]
dl'd from here http://code52.org/carnac/ and the direct link is https://github.com/downloads/Code52/carnac/Carnac.zip

See screenshot of the error. Never seen this error before.
![image](https://user-images.githubusercontent.com/14054664/59981885-1cdf2d80-9602-11e9-8772-5e366c12c5e1.png)

Clicking on debug which made the app run.

**Comment by stephen147** [comment]
This fixed.

**Comment by flohock** [comment]
I had the exact same problem today after downloading carnac from the same site. I tried several times and clicked "abort" each time.

Once I clicked on "debug" as stephen147 suggested, it launched carnac. Then, after exiting and launching it again, it launched properly.

Also, it appears you have to do it again (click on "debug"), if you move the folder containing carnac.
