### ISSUE TITLE
Mouse events

### ISSUE THREAD

**Issue by vv7v7** [Code52/carnac#227]
Dear Developer,

Thank you for this project.
Although, is it possible to get such program capture and show mouse events, like wheel scroll(up, down) or custom mouse clicks?

**Comment by unreal-skif** [comment]
https://github.com/bfritscher/carnac/tree/show-modifier-keys-while-down

**Comment by rickstaa** [comment]
@unreal-skif I was wondering when the mouse click display functionality will be merged into the master branch? I tested the fork of bfritscher and it still has some problems:

- Popup Fade Delay is not working
- Monitor offset also offsets the mouse click position.

**Comment by lyscop** [comment]
> https://github.com/bfritscher/carnac/tree/show-modifier-keys-while-down

It still can not set the time of the information shows on the screen.
