### ISSUE TITLE
Disabling mouse clicks still keep the click visual + disabling mouse visual while keeping mouse clicks

### ISSUE THREAD

**Issue by franckberneron** [Code52/carnac#229]
Hi,
Thanks for the great product.
I tried to get rid of the mouse-click visual but couldn't. Even when I choose "Disable mouse clicks", the mouse visual still shows up.
I suggest two checkboxes :
- Disable mouse visual only
- Disable mouse clicks & mouse visual
Thanks !

**Comment by bfritscher** [comment]
I guess you are talking about my fork I updated it today.
https://github.com/bfritscher/carnac/releases

**Comment by 0maunz0** [comment]
> I guess you are talking about my fork I updated it today.
> https://github.com/bfritscher/carnac/releases

Thank you a lot for that one, makes it even better!

**Comment by franckberneron** [comment]
Thanks, for your reply, I'll try it out ! 😉
