### ISSUE TITLE
Trapmine marks installer as Malicious.moderate.ml.score

### ISSUE THREAD

**Issue by Some-T** [Code52/carnac#236]
https://www.virustotal.com/gui/file/b70aabbb869ca9f0db78515389e2b3b73480a0ef17c430fc42cd83d008d61e69/detection

**Comment by shiftkey** [comment]
@Some-T any more context you can provide? I google'd for what this actual represents and couldn't find anything helpful from my side, so I believe this is a false positive.

**Comment by Some-T** [comment]
No sorry, I just used that site as per the link.

**Comment by shiftkey** [comment]
I don't really have much actionable things to work with here, but if someone knows how I can reach out to Trapmine about addressing this false positive, I'm happy to try my luck.
