### ISSUE TITLE
keymaps for different applications

### ISSUE THREAD

**Issue by tricktresor** [Code52/carnac#244]
Hey there!
I understand how to define keymaps (*.yml file) for different applications. Not that hard...
But: how do I map my keymap to my specific application?
Or in other word: How does carnackeys know which application I am using?

Thanks for any hint!
Enno

**Comment by bfritscher** [comment]
In the yml file you have the entry "process: nameofprocess" which is used to do the matching.
Internally it used https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processname?view=netcore-3.1#System_Diagnostics_Process_ProcessName

So it should be what you see in task manager under details/name without the .exe

**Comment by tricktresor** [comment]
thanks for your fast reply!
GROUP in yml file and file name are not relevant?

it does not work correctly for me. 
the process has sub processes which are not respected.
The display works only for 1 key stroke in main process although I have defined some more.

But that's okay. because the key strokes of the sub processes also depend on the executed transaction which will not be covered by carnackeys (SAPGUI/ saplogon.exe).

Thanks!
Enno

**Comment by bfritscher** [comment]
From what I could find neither filename or group are referenced in the code, but you can leave process with an empty value (only whitespace) and it should match any process. (Otherwise you will have to duplicate your keymap file for each subprocess name)
