### ISSUE TITLE
Doesn't capture Windows Terminal keystrokes

### ISSUE THREAD

**Issue by JustinGrote** [Code52/carnac#250]
If used with Windows Terminal, it is unable to capture the keystrokes, even "native" ones that aren't passed through to the terminal.

**Comment by sitiom** [comment]
I had this problem before; this seems to have been fixed in the latest version of Windows Terminal.

**Comment by JustinGrote** [comment]
@sitiom confirmed! closing.

**Comment by BearyDevs** [comment]
I have this issue too. Can I fix it on my window terminal

**Comment by sitiom** [comment]
Continued in #290
