### ISSUE TITLE
YML keycode for Scroll Wheel?

### ISSUE THREAD

**Issue by msmcq2003** [Code52/carnac#263]
I've tried WheelUp/WheelDown and ScrollUp/ScrollDown.  Using ver 2.3.13.

**Comment by bfritscher** [comment]
Try: VolumeUp VolumeDown ;-)

**Comment by msmcq2003** [comment]
Works! Thank you! I never would have guessed that one.

**Comment by bfritscher** [comment]
I had to look it up in the code ;-) Since it works, I suggest you close the issue
