### ISSUE TITLE
Keymap yml for Kdenlive

### ISSUE THREAD

**Issue by candideu** [Code52/carnac#300]
Hello,

I created a keymap for the Kdenlive video editor here, in case anyone needs it: https://github.com/candideu/kdenlive-keymap/blob/main/kdenlive.yml

I didn't see the keymaps in the source code, so I wasn't sure how to create a merge request.

**Comment by computamike** [comment]
hi @candideu  - I'm not involved in the project - just a regular user like you - but here's how I think that the pull request would work.

If you click the fork button..
![image](https://user-images.githubusercontent.com/464876/143437978-5ad0c8d5-c17f-4d97-ace8-bf99c6275090.png)
]

You can then create your own fork of carnac.

Then you can add this file into your fork at the correct location, and from there create a pull request.

I've found other keymaps in the carnac logic folder carnac/src/Carnac.Logic/Keymaps/ folder : 
![image](https://user-images.githubusercontent.com/464876/143438392-4ca1b71b-e0b1-4752-af4d-9996aadaa934.png)

From what I can see you'd also have to include them in the csproj file - but these seem to be just to copy it to the output folder.
![image](https://user-images.githubusercontent.com/464876/143438641-d49c3bca-84ec-4bb8-ae61-c0188722cb02.png)

**Comment by candideu** [comment]
@computamike Thank you! This is exactly what I was looking for!
