### ISSUE TITLE
win8 64 cannot be used.

### ISSUE THREAD

**Issue by zhenlonghe** [Code52/carnac#56]

**Comment by gdh1995** [comment]
This problem occurs on my Win10 Creator v1703 x64 build 15063.413. The call stack is almost the same.

On my Win10 are .Net 4.0/4.5 from VS2010, VS2012 (without updates/hotfixes) and .Net 3.5 installe by DISM.

**Comment by PhiLhoSoft** [comment]
First try of Carnac 2.3.3 on Windows 10 (64-bit).
I get this error message. Same stack trace and all.
Carnac won't start. Not sure what to do…
