### ISSUE TITLE
Hello Squirrel, Goodbye ClickOnce

### ISSUE THREAD

**Issue by shiftkey** [Code52/carnac#69]
It's time: https://github.com/squirrel/squirrel.windows

Also, this is probably worth using https://github.com/flagbug/ClickOnceToSquirrelMigrator

cc @flagbug

Also we should stop using @JakeGinnivan's blob storage and use GitHub Releases.

**Comment by flagbug** [comment]
![thumb_up](https://cloud.githubusercontent.com/assets/964691/5836259/66c22656-a173-11e4-8363-56b3804d571d.gif)

Let me know if you have any problems with the migration!

**Comment by CumpsD** [comment]
Would love to see this, could help to turn it into I can put on a portable stick instead of the ClickOnce thing :)

**Comment by JakeGinnivan** [comment]
Made this up for grabs. I don't have time to learn Squirrel at the moment and not sure @shiftkey has the time either

**Comment by shiftkey** [comment]
@JakeGinnivan yep. I really don't have a spare day until after BUILD at this stage, if I'm lucky.

**Comment by shiftkey** [comment]
Closing this out in favour of #125 - I've already deprecated the ClickOnce package in #128 in favour of Chocolatey.
