### ISSUE TITLE
Add Chocolatey Package

### ISSUE THREAD

**Issue by shiftkey** [Code52/carnac#70]

**Comment by luisrudge** [comment]
:+1:

**Comment by DustinVenegas** [comment]
To do this we need a source of truth for versioned bundles. Does anyone care if we add releases to this repository? The click-once package is cool, but I'm not sure who's hosting it and they don't version well with Chocolatey (currently).

**Comment by shiftkey** [comment]
> Does anyone care if we add releases to this repository?

I'm down with this.

> The click-once package is cool, but I'm not sure who's hosting it and they don't version well with Chocolatey (currently).

They're hosted by @JakeGinnivan currently.

**Comment by JakeGinnivan** [comment]
We are kinda waiting for #69 to be done. Happy for someone to step up, I can help advise/answer questions

**Comment by DustinVenegas** [comment]
A quick choco install is available in my [choco packages](https://github.com/DustinVenegas/chocolatey-packages/tree/master/carnac). You can try it out with `choco install -s https://www.myget.org/F/dustinvenegas/ carnac`. It installs to the Chocolatey bin-root with and adds a user specific start menu icon.

A couple of quick questions to get this show on the road. 

* Who wants maintain the package on Chocolatey.org? I haven't uploaded it under my account in case Code52 wants the official maintenance. 
* Can we start cutting semantic releases? I assumed the package is 1.0.0.0 in the nuspec. 
* Can we start using [Github releases](https://github.com/blog/1547-release-your-software)? I prefer Chocolatey updates to auto-updating.

**Comment by shiftkey** [comment]
@DustinVenegas thanks for this - are you interested in PRing the nuspec file into the repo to discuss it further?

> Who wants maintain the package on Chocolatey.org?

I'm happy to look after it initially - I can invite others if they want to get involved.

> Can we start cutting semantic releases? 

That seems reasonable - let's talk about this in the PR.

> Can we start using Github releases?

If we have Squirrel updates in place, that's not going to play nice with this. Perhaps we need a way to disable auto-updating in the build for these packages.

**Comment by DustinVenegas** [comment]
@shiftkey where in source would you like the choco nuget package placed?

**Comment by shiftkey** [comment]
@DustinVenegas the root of the repository is fine with me

**Comment by ghuntley** [comment]
:hotsprings: can't wait till this drops.

**Comment by luisrudge** [comment]
updates? :D

**Comment by DustinVenegas** [comment]
I haven't heard anything it needs.

**Comment by shiftkey** [comment]
Sorry, we've totally dropped the ball on this. Looks like AppVeyor isn't configured right and the PRs sit, unloved.

I'll chat with @JakeGinnivan about this during the week (or just take it over) to see what we need to do here.

**Comment by shiftkey** [comment]
Awaiting review: https://chocolatey.org/packages/carnac/1.0.0.22

**Comment by ghuntley** [comment]
:cake:
