### ISSUE TITLE
Show Win key pressed after unlocking PC

### ISSUE THREAD

**Issue by peteraritchie** [Code52/carnac#73]
For discussion, I'm not sure this is a bug in Carnac. After I unlock a PC, Carnac displays the <kbd>Win</kbd> key symbol beside every keystroke.  For example, after I unlock my computer, if I press <kbd>x</kbd>, carnac shows <kbd>Win + x</kbd>; but the Windows Power User Menu does not appear so Windows doesn't think I pressed <kbd>Win + x</kbd>.

**Comment by cbo100** [comment]
I've only had a quick look at this, but to me it seems possible it's Windows not sending the Key Up message. Not really a bug, more like a limitation. Possibly a side effect of the secure desktop?

The `winKeyPressed` flag gets stuck on in `KeyProvider.DetectWindowsKey` as it seems the `InterceptKeys.HookCallback` is never notified of the `Win` key being released in some cases.

Reproducible:

1. Press <kbd>Win + L</kbd>
2. Ensure to hold the <kbd>Win</kbd> key down until the "Press CTRL+ALT+DEL to Unlock" screen appears
3. Upon unlocking the desktop again all keystrokes are reported as <kbd>Win+[KEY]</kbd>

If you very quickly release the <kbd>Win</kbd> key before the secure desktop is loaded then it does not have the problem.

**Comment by peteraritchie** [comment]
Okay, I see what's happening.  I had originally thought it was a bug in Windows (which I was going to use a fuel for something else...) but it does seem to be something in Carnac.  I've send a pull request with a change for this to simulate a key up event on the unlock of the desktop (if needed).

**Comment by JakeGinnivan** [comment]
Thanks for this. @shiftkey any thoughts on when you can migrate to squirrel and how we do deployment? Or should I just push clickonce update on the weekend?

**Comment by shiftkey** [comment]
@JakeGinnivan let's just push a ClickOnce update for now
