### ISSUE TITLE
carnac stop working when process no longer exist

### ISSUE THREAD

**Issue by michaelloewenstein** [Code52/carnac#89]
Carnac stops working in the following case:

Open a console (for example: carnac\tools\xunit\xunit.console.x86.exe).
Try to create a scenario where you input a key and the console exits before carnac displays your key.
The app will stop working since GetAssociatedProcess() method won't find the process Id associated and an exception arises. Now the app no longer response.
![capture](https://cloud.githubusercontent.com/assets/1331783/6914612/f232fbf0-d794-11e4-91b9-3484e8b5c349.PNG)

**Comment by shiftkey** [comment]
This will be fixed in build 2.0.0.55.
