### ISSUE TITLE
Create AppVeyor Build

### ISSUE THREAD

**Issue by DustinVenegas** [Code52/carnac#95]
Create a quick build on AppVeyor using the current build scripts.

**Comment by DustinVenegas** [comment]
If a project administrator merges, creates an AppVeyor project, and changes the badge then this is complete.

**Comment by shiftkey** [comment]
The first package for Carnac is awaiting review. It links to this release: https://github.com/Code52/carnac/releases/tag/1.0.0.22

Let me know if there's any tweaks you need here. And thanks for laying the groundwork @DustinVenegas!
